name: Relase to NPM registry

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        description: 'Runner to use'
        default: 'ubuntu-latest'
      node-version:
        type: number
        description: 'Node version to use'
        default: 20
      before-publish:
        type: string
        description: 'Command to run before publishing'
        default: 'echo "No command to run"'

    secrets:
      GITHUB_TOKEN:
        required: true
      NPM_TOKEN:
        required: true

    outputs:
      published:
        description: 'Whether a changeset was published'
        value: ${{ jobs.release.outputs.published }}
      publishedPackages:
        description: 'Published packages'
        value: ${{ jobs.release.outputs.publishedPackages }}
      hasChangesets:
        description: 'Whether there are changesets'
        value: ${{ jobs.release.outputs.hasChangesets }}
      pullRequestNumber:
        description: 'Pull request number'
        value: ${{ jobs.release.outputs.pullRequestNumber }}
      transformPackages:
        description: 'Packages to build'
        value: ${{ jobs.release.outputs.transformPackages }}

jobs:
  release:
    name: Versioning and Release
    runs-on: ${{ inputs.runs-on }}

    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
      pullRequestNumber: ${{ steps.changesets.outputs.pullRequestNumber }}
      transformPackages: ${{ steps.transform-packages.outputs.packages }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # related to issue, https://github.com/changesets/action/issues/201
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Install Changeset CLI
        run: yarn global add @changesets/cli

      - name: Create Versioning Pull Request
        id: changesets
        uses: changesets/action@v1.4.2
        with:
          createGithubReleases: true
          version: changeset version
          publish: ${{ inputs.before_publish }} && changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Transform Packages
        id: transform-packages
        run: |
          PACKAGES=$(echo $PACKAGES | jq -c 'map_values({name:.name,ref:"refs/tags/\(.name)@\(.version)"})')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT
        env:
          PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}

      - name: Echo Changeset output
        run: |
          echo "Changeset published - ${{ steps.changesets.outputs.published }}"
          echo "Changeset publishedPackages - ${{ steps.changesets.outputs.publishedPackages }}"
          echo "Changeset hasChangesets - ${{ steps.changesets.outputs.hasChangesets }}"
          echo "Changeset pullRequestNumber - ${{ steps.changesets.outputs.pullRequestNumber }}"
          echo "Packages to build - ${{ steps.transform-packages.outputs.packages }}"
